### ISSUE TITLE
Spreading prismoss should have a chance to spawn prismarite crystals

### ISSUE THREAD

**Issue by TheDeviantCrafter** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#103] opened 2024-01-11 02:26 UTC
**Describe your suggestion.**
Spreading prismoss by applying bone meal has a chance to grow prismoss sprouts. I think it should grow prismarite crystals as well.

**Additional context**
As far as I can tell, prismarite is not renewable. This would also make prismaglass and the other 2 prismarite crystal shapes craftable since they can already be made from normal crystals.

**Comment by UHQ-GAMES** [comment] 2024-01-11 13:36
it was something I considered but prismarite crystals are non renewable by design so at least for now thats intentional behaviour

**Comment by UHQ-GAMES** [comment] 2024-02-17 06:22
because the original idea was to have this as a rare decoration but because of an oversight on my part they're much more common than I want. this may change in the future but for now I'm pinning this and closing it for future use

**Closed by UHQ-GAMES** 2024-02-17 06:22 UTC
Labels: feature, pinned

**Comment by TheDeviantCrafter** [comment] 2024-02-17 19:46
They could spread like mushrooms within prismoss biomes only. If the rate is slow enough, they would be technically renewable but requires massive farms to get a decent supply.

**Comment by UHQ-GAMES** [comment] 2024-02-18 00:46
ohhh thats actually a good idea, ill keep that in mind!

**Comment by ImEnoan** [comment] 2024-07-05 20:28
Renewable Prismarite would be great, if you are looking for other options:

maybe an interaction to turn amethyst into prismarite? Either as like a crafting recipe or something more "in world" like amethyst being converted into prismarite when nearby prismoss is bonemealed

**Comment by ThomSimoneau** [comment] 2025-03-02 19:43
Yo! Sorry for the necro comment, I tried checking if this was something that was changed in later releases of the mod, but is Prismarite still non-renewable? I was wondering if I let some on the hanging prismarite at they natural generation site if they would "grow" back to their original state.

Thank you! :)

**Comment by broteleski** [comment] 2026-02-14 09:23
I think the hanging prismarite would make sense to grow down over time for a renewable resource as well. I've used around 5k shards as it is already and just collecting them is very time consuming. Perhaps it could ast as drip stone where if you put it under prismoss block and then add water or maybe a new prismatic liquid on top of the block to allow it to grow and be an indefinite resource.
Along with that when crafting the glass sometimes it will use the already colored glass rather than the clear vanilla glass when shift clicking it into recipes, therefore halfing the glass you get.  If no changes at all, that's okay. It's a beautiful mod and I'm happy it exists at all.
