### ISSUE TITLE
Bug Report - Forge Server does not start with Mod

### ISSUE THREAD

**Issue by Dwitch87** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#2] opened 2023-06-14 10:03 UTC
**Describe the bug**
Server does not start at all - both Forge versions

No problems on Clientside - starting Minecraft and creating world is working fine!
Only Server is making problems

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
Steps to reproduce the bug:

**Version**
Minecraft Versions:
1.20.1-47.0.1
1.20-46.0.14
Modloader Version:
What is Modloader Version?
Using Forge
1.20.1-47.0.1
1.20-46.0.14

Mod Version:
In Forge 1.20
RegionsUnexploredForge-0.4.1_1+1.20.jar
and
RegionsUnexploredForge-0.4.1+1.20.jar
(--> not in screenshots)

In Forge 1.20.1
RegionsUnexploredForge-0.4.1_1+1.20.1.jar

and of Course
TerraBlender-forge-1.20-3.0.0.163.jar
--> Only Terrablender is working fine and server is starting normal

**Screenshots**
In Forge 1.20
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/122459371/5f6796f2-28eb-432a-ad73-e339d94acc7d)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/122459371/e767ad6f-2c76-4e86-863a-180b5d52c1d6)

In Forge 1.20.1
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/122459371/6db420d9-0b50-46b3-a6b3-4f987e15aa30)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/122459371/89d199c5-9217-4336-b484-aff2445be1ba)

ZIP File - contains Logs for both Forge Versions
[RegionsUnexplored-Logs.zip](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/11743231/RegionsUnexplored-Logs.zip)

####

Maybe I did something wrong?

**Comment by UHQ-GAMES** [comment] 2023-06-14 20:38
Hmm this is odd, I test on a server before I released so I'll do some double checks, I'll message here when I have more info, thanks!

**Comment by Dwitch87** [comment] 2023-06-15 07:26
Hi,
thank you!
Just, if needed, I'm running Ubuntu 22.04.1 LTS with latest updates/upgrades
Java Version is "openjdk version "19.0.2" 2023-01-17" and more details below!
Thanks

cat /proc/version
Linux version 5.15.0-73-generic (buildd@bos03-amd64-060) (gcc (Ubuntu 11.3.0-1ub                                                                                                                  untu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #80-Ubuntu SMP Mon                                                                                                                   May 15 15:18:26 UTC 2023

java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04)
OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)

**Comment by Dwitch87** [comment] 2023-06-16 14:53
Hi,
I updated to:
Forge 1.20.1-47.0.3
TerraBlender-forge-1.20.1-3.0.0.164
And still same error.
So its not been fixed by updating these to  files.

If you want to, I can test anything tomorrow (in about 16 hours).
As I live in Germany, it is now 17 o'Clock for me!

Thanks and best regards
Dennis

**Comment by UHQ-GAMES** [comment] 2023-06-17 01:57
ay no worries, as of now im still trying to replicate the issue

**Comment by UHQ-GAMES** [comment] 2023-06-18 04:57
sadly i havent been able to replicate the issue. are you running Regions on its own with terrablender?

**Comment by Dwitch87** [comment] 2023-06-18 09:54
Hey!
I just tested my old minecraft server (notebook running ubuntu latest version) but same error.
Installed forge 47.0.3 and just Terrablender 164 and your latest forge version.

What do you mean, with "running Regions on its own with terrablender"?
I just installed it for your mod. Dont know, how to play with terrablender only or event dont know what it is doing.
Thanks and best regards

**Comment by Dwitch87** [comment] 2023-06-18 11:18
Hi,
I just encountered an crash on my Windows Client.
Playing on my server, rightclick on a chest.
Regions Unexplored is installed on my client, but not on my server:
Exit-Code: -1
The game crashed whilst container click
Error: java.lang.NullPointerException: Registry Object not present: regions_unexplored:alpha_log
I disabled the mod now, for my client, too.

**Comment by UHQ-GAMES** [comment] 2023-06-20 01:18
Fixed it! Accidently registered wood types in common setup rather than client setup. Will be fixed in 0.4.2 tomorrow! as for the above crash, that error could be caused by the mod being installed on client but not server. typically having mods loaded that arent present on server can cause issues.

**Comment by UHQ-GAMES** [comment] 2023-06-20 01:19
Closing issue as complete. Fixed wood types registered on incorrect setup phase, will be fixed in 0.4.2 tomorrow.

**Closed by UHQ-GAMES** 2023-06-20 01:19 UTC
Labels: bug
