### ISSUE TITLE
Generating Chunk on World creation crash Bug Report 1.19.2

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#49] opened 2023-10-21 03:30 UTC
**Describe the bug**
With using Regions Unexplored 0.5.3, I cannot create a world. It crashes to desktop. Reverting back does not repair a damaged world. 

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.
[crash-2023-10-20_20.23.09-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13059753/crash-2023-10-20_20.23.09-server.txt)
[crash-2023-10-20_20.14.11-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13059754/crash-2023-10-20_20.14.11-server.txt)
[crash-2023-10-20_19.52.19-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13059755/crash-2023-10-20_19.52.19-server.txt)

**How To Reproduce**
Steps to reproduce the bug:
1. Launch modpack.
2. Create a new world OR open an existing world.
3. crash.

**Version**
Minecraft Version: 1.19.2

Modloader Version: Forge 43.3.0

Mod Version: 0.5.3

**Screenshots**
None.

It does mention Blueprint in the latest crash report so is it an issue with Blueprint or with Terralith? I read something specifically about sparse jungles.

**Comment by ZephyrWindSpirit** [comment] 2023-10-21 04:01
Upon testing the same mod version without terralith or any other biome-affecting mods in all the mods 8, Regions Unexplored works to generate a world. 
Testing the same modpack with terralith and regions unexplored... crash.
Specifically: [20/10/2023 20:54:19 PM] Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:sparse_jungle]=net.minecraft.world.level.biome.Biome@4fb2ad3}, Reference{ResourceKey[minecraft:worldgen/biome / regions_unexplored:rainforest]=net.minecraft.world.level.biome.Biome@46b51507}]
[crash-2023-10-20_20.54.16-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13059806/crash-2023-10-20_20.54.16-server.txt)

**Comment by ZephyrWindSpirit** [comment] 2023-10-21 04:07
When I investigated the issue of feature order cycle, it appears to be an issue with Cyclic, per the stardust labs discord announcements! So it may not be your mod after all and I'm very sorry for bothering you if that's the case.

**Comment by Reshy** [comment] 2023-10-21 09:28
I don't use Cyclic and I still get this crash.

**Comment by UHQ-GAMES** [comment] 2023-10-22 06:49
this is the same issue ru and terralith had in 1.20.1 which was fixed on terraliths side. already reported to the terralith devs!

**Comment by UHQ-GAMES** [comment] 2023-10-22 06:59
closing as duplicate of #50

**Closed** 2023-10-22 06:59 UTC

**Comment by BlackAures1** [comment] 2023-10-27 18:59
I don't have terralith, but the crash is the same as other users
[crash-2023-10-27_21.48.09-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13192287/crash-2023-10-27_21.48.09-server.txt)
[crash-2023-10-27_21.50.49-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13192288/crash-2023-10-27_21.50.49-server.txt)
