### ISSUE TITLE
Bug Report Broken Boat Recipe

### ISSUE THREAD

**Issue by OminousDiscovery** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#72] opened 2023-11-11 22:39 UTC
**Describe the bug**
the maple boat is crafted with a chest and a plank and now that im looking at the recipes a TON of boats have this issue

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
Steps to reproduce the bug:

**Version**
Minecraft Version: 1.20.1

Modloader Version: 47.1.3 forge

Mod Version: 0.5.3

**Screenshots**

**Comment by UHQ-GAMES** [comment] 2023-11-11 23:51
duplicate of #64

fixed for 0.5.4

**Closed** 2023-11-11 23:51 UTC
Labels: duplicate, complete
