### ISSUE TITLE
Crash with Terralith (1.19.2)

### ISSUE THREAD

**Issue by zmqrcoo** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#58] opened 2023-10-29 18:58 UTC
singleplayer world crashes after a few minutes of playtime, removed RegionsUnexplored and i was able to play normally.

latest.log: https://mclo.gs/t1f43I4

minecraft 1.19.2 forge 43.3.0

RegionsUnexplored 0.5.3

**Comment by UHQ-GAMES** [comment] 2023-10-30 01:11
this is caused by Terralith, it was fixed in terralith [v2.3.12](https://modrinth.com/mod/terralith/version/2.3.12)

closing as duplicate of #50

**Closed by UHQ-GAMES** 2023-10-30 01:11 UTC
